Try creating parent directory before baling out
fastmail/mint-tag pull request #15
Opened 2020-08-28 02:30 UTC by Davis-A

Mostly a convenience thing.  

For example if the config path is /tmp/foo/bar then anyone using a tmpfs has to manually recreate /tmp/foo after every reboot because it bails out if it cant chdir into it.

2020-08-28 12:54 UTC, mmcclimon requested changes
I think the thing you suggested in Slack is slightly better, which is: check for the existence of the directory and make it if necessary, then chdir.

I would write this in a single line: `$dir->parent->mkpath unless $dir->parent->is_dir`.

2020-08-28 12:54 UTC, mmcclimon commented on lib/App/MintTag.pm
> +    unless (chdir $dir->parent) {
This is a weird way to do this; it's possible that chdir could fail because the path exists but is a file, for example.

2020-08-28 12:54 UTC, mmcclimon commented on lib/App/MintTag.pm
> +      Path::Tiny::path($dir->parent)->mkpath;
`->parent` on a Path::Tiny object gives you another Path::Tiny, so the `path()` here is redundant; you can just write `$dir->parent->mkpath`.

2020-08-28 12:55 UTC, mmcclimon commented
(Also I just noticed that your commit message misspells "bailing".

2020-08-31 02:11 UTC, Davis-A commented
Fixed

2020-08-31 14:52 UTC, mmcclimon commented
I have applied this with a different commit message, thanks!

2020-08-31 14:52 UTC, closed without merging